export const PRFILE_TYPE = {
    AGENT: 1,
    CLIENT: 2,
    VENDOR: 3,
    OTHER: 4,
};

export const MAJOR_VENDOR_TYPE_AIRLINES = {
    AMERICAN_AIRLINES: 146,
    DELTA_AIRLINES: 259,
    UNITED_AIRLINES: 564,
};
